### ISSUE TITLE
No module named 'lie_learn.representations.SO3.irrep_bases'

### ISSUE THREAD

**Issue by EricPengShuai** [jonkhler/s2cnn#56]
@kkokilep @mariogeiger In your MNIST example,  running S2CNN encounters the following problem about lie_learn module.
```python
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\peng\anaconda3\envs\pytorch_1.8\lib\site-packages\lie_learn\representations\SO3\wigner_d.py", line 5, in <module>
    from lie_learn.representations.SO3.irrep_bases import change_of_basis_matrix
ModuleNotFoundError: No module named 'lie_learn.representations.SO3.irrep_bases'
```

_Originally posted by @EricPengShuai in https://github.com/jonkhler/s2cnn/issues/52#issuecomment-893144464_

**Comment by mariogeiger** [comment]
Hi,
I'm sorry because this repository is not maintained since a long time. I have the plan to reproduce the architecture and experiments of this repository within the e3nn library that I maintain. The only missing component is the SO3 Fourier transform.

**Comment by EricPengShuai** [comment]
@mariogeiger Sorry to disturb you, can I implement spherical CNNs (s2cnn) with the help of e3cnn? Or do you have time to rewrite and maintain this repository? 
Thanks in advance!

**Comment by mariogeiger** [comment]
Here is an implementation using e3nn:
https://github.com/e3nn/e3nn/tree/main/examples/s2cnn/mnist

There still might be an issue with this code, I remember it was not training properly last time I tried. 

The fast Fourier transform is still missing for the so3 transformation, here is the current naive implementation: https://github.com/e3nn/e3nn/blob/main/e3nn/o3/_so3grid.py

**Comment by nhey** [comment]
@mariogeiger Thanks for the e3nn implementation. The test accuracy is about 40% for me after 20 epochs, do you have any ideas as to what the issue might be?
